language: csharp
solution: ArdupilotMega.sln

notifications: 
   webhooks: 
     urls: 
       - https://webhooks.gitter.im/e/e1224e020cf9b5a91a8c 
     on_success: change  # options: [always|never|change] default: always 
     on_failure: always  # options: [always|never|change] default: always 
     on_start: false     # default: false 
